x-logging: &default-logging
    driver: json-file
    options:
      max-file: "5"
      max-size: "10m"

x-restarts: &default-restart
    on-failure:3

services:
  postgres:
    image: postgres:16.4-alpine
    logging: *default-logging
    restart: *default-restart
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: disc-msg-store-server
      POSTGRES_PASSWORD: ${DISC_MSG_STORE_SERVER_DB_PASSWORD}
      POSTGRES_DB: disc-msg-store-server
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U disc-msg-store-server"]
      interval: 2s
      timeout: 1s
      retries: 5

  discord-message-store-server:
    image: ghcr.io/ayussh-verma/discord-message-store-server:latest
    logging: *default-logging
    restart: *default-restart
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DISC_MSG_STORE_SERVER_DB_JDBC_URL: jdbc:postgresql://postgres:5432/disc-msg-store-server
      DISC_MSG_STORE_SERVER_DB_PASSWORD: ${DISC_MSG_STORE_SERVER_DB_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/actuator/health"]
      interval: 2s
      timeout: 1s
      retries: 5

  discord-message-store-client:
    image: ghcr.io/ayussh-verma/discord-message-store-client:latest
    logging: *default-logging
    restart: *default-restart
    depends_on:
      discord-message-store-server:
        condition: service_healthy
    environment:
      DISC_MSG_STORE_CLIENT_API_BASE_URL: http://discord-message-store-server:8100
      DISC_MSG_STORE_CLIENT_BOT_TOKEN: ${DISC_MSG_STORE_CLIENT_BOT_TOKEN}
      DISC_MSG_STORE_CLIENT_BOT_GUILD_ID: ${DISC_MSG_STORE_CLIENT_BOT_GUILD_ID}

volumes:
  db-data:
